#!/bin/bash
java -jar ./compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --js CTMWorker.js --js lzma.js --js ctm.js >CTMWorkerMin.js

#java -jar ./compiler.jar --compilation_level SIMPLE_OPTIMIZATIONS --compute_phase_ordering --js concat.js >compiled.js
#java -jar ./compiler.jar --compilation_level ADVANCED_OPTIMIZATIONS --js concat.js >compiled.js
#scp compiled.js tux.creatis.insa-lyon.fr:/home/valette/public_html/meshView/compiled.js
