importScripts("lzma.js","ctm.js");self.onmessage=function(a){for(var b=[],c=0;c<a.data.offsets.length;c++){var d=new CTM.Stream(a.data.data);d.offset=a.data.offsets[c];b[c]=new CTM.File(d)}self.postMessage(b);self.close()};var LZMA=LZMA||{};LZMA.OutWindow=function(){this._windowSize=0};LZMA.OutWindow.prototype.create=function(a){if(!this._buffer||this._windowSize!==a)this._buffer=[];this._windowSize=a;this._streamPos=this._pos=0};LZMA.OutWindow.prototype.flush=function(){var a=this._pos-this._streamPos;if(a!==0){for(;a--;)this._stream.writeByte(this._buffer[this._streamPos++]);if(this._pos>=this._windowSize)this._pos=0;this._streamPos=this._pos}};
LZMA.OutWindow.prototype.releaseStream=function(){this.flush();this._stream=null};LZMA.OutWindow.prototype.setStream=function(a){this.releaseStream();this._stream=a};LZMA.OutWindow.prototype.init=function(a){if(!a)this._pos=this._streamPos=0};LZMA.OutWindow.prototype.copyBlock=function(a,b){var c=this._pos-a-1;if(c<0)c+=this._windowSize;for(;b--;){if(c>=this._windowSize)c=0;this._buffer[this._pos++]=this._buffer[c++];this._pos>=this._windowSize&&this.flush()}};
LZMA.OutWindow.prototype.putByte=function(a){this._buffer[this._pos++]=a;this._pos>=this._windowSize&&this.flush()};LZMA.OutWindow.prototype.getByte=function(a){a=this._pos-a-1;if(a<0)a+=this._windowSize;return this._buffer[a]};LZMA.RangeDecoder=function(){};LZMA.RangeDecoder.prototype.setStream=function(a){this._stream=a};LZMA.RangeDecoder.prototype.releaseStream=function(){this._stream=null};
LZMA.RangeDecoder.prototype.init=function(){var a=5;this._code=0;for(this._range=-1;a--;)this._code=this._code<<8|this._stream.readByte()};LZMA.RangeDecoder.prototype.decodeDirectBits=function(a){for(var b=0,c;a--;){this._range>>>=1;c=this._code-this._range>>>31;this._code-=this._range&c-1;b=b<<1|1-c;if((this._range&4278190080)===0){this._code=this._code<<8|this._stream.readByte();this._range<<=8}}return b};
LZMA.RangeDecoder.prototype.decodeBit=function(a,b){var c=a[b],d=(this._range>>>11)*c;if((this._code^2147483648)<(d^2147483648)){this._range=d;a[b]+=2048-c>>>5;if((this._range&4278190080)===0){this._code=this._code<<8|this._stream.readByte();this._range<<=8}return 0}this._range-=d;this._code-=d;a[b]-=c>>>5;if((this._range&4278190080)===0){this._code=this._code<<8|this._stream.readByte();this._range<<=8}return 1};LZMA.initBitModels=function(a,b){for(;b--;)a[b]=1024};
LZMA.BitTreeDecoder=function(a){this._models=[];this._numBitLevels=a};LZMA.BitTreeDecoder.prototype.init=function(){LZMA.initBitModels(this._models,1<<this._numBitLevels)};LZMA.BitTreeDecoder.prototype.decode=function(a){for(var b=1,c=this._numBitLevels;c--;)b=b<<1|a.decodeBit(this._models,b);return b-(1<<this._numBitLevels)};LZMA.BitTreeDecoder.prototype.reverseDecode=function(a){for(var b=1,c=0,d=0,e;d<this._numBitLevels;++d){e=a.decodeBit(this._models,b);b=b<<1|e;c|=e<<d}return c};
LZMA.reverseDecode2=function(a,b,c,d){for(var e=1,i=0,f=0,g;f<d;++f){g=c.decodeBit(a,b+e);e=e<<1|g;i|=g<<f}return i};LZMA.LenDecoder=function(){this._choice=[];this._lowCoder=[];this._midCoder=[];this._highCoder=new LZMA.BitTreeDecoder(8);this._numPosStates=0};LZMA.LenDecoder.prototype.create=function(a){for(;this._numPosStates<a;++this._numPosStates){this._lowCoder[this._numPosStates]=new LZMA.BitTreeDecoder(3);this._midCoder[this._numPosStates]=new LZMA.BitTreeDecoder(3)}};
LZMA.LenDecoder.prototype.init=function(){var a=this._numPosStates;for(LZMA.initBitModels(this._choice,2);a--;){this._lowCoder[a].init();this._midCoder[a].init()}this._highCoder.init()};LZMA.LenDecoder.prototype.decode=function(a,b){if(a.decodeBit(this._choice,0)===0)return this._lowCoder[b].decode(a);if(a.decodeBit(this._choice,1)===0)return 8+this._midCoder[b].decode(a);return 16+this._highCoder.decode(a)};LZMA.Decoder2=function(){this._decoders=[]};
LZMA.Decoder2.prototype.init=function(){LZMA.initBitModels(this._decoders,768)};LZMA.Decoder2.prototype.decodeNormal=function(a){var b=1;do b=b<<1|a.decodeBit(this._decoders,b);while(b<256);return b&255};LZMA.Decoder2.prototype.decodeWithMatchByte=function(a,b){var c=1,d,e;do{d=b>>7&1;b<<=1;e=a.decodeBit(this._decoders,(1+d<<8)+c);c=c<<1|e;if(d!==e){for(;c<256;)c=c<<1|a.decodeBit(this._decoders,c);break}}while(c<256);return c&255};LZMA.LiteralDecoder=function(){};
LZMA.LiteralDecoder.prototype.create=function(a,b){var c;if(!(this._coders&&this._numPrevBits===b&&this._numPosBits===a)){this._numPosBits=a;this._posMask=(1<<a)-1;this._numPrevBits=b;this._coders=[];for(c=1<<this._numPrevBits+this._numPosBits;c--;)this._coders[c]=new LZMA.Decoder2}};LZMA.LiteralDecoder.prototype.init=function(){for(var a=1<<this._numPrevBits+this._numPosBits;a--;)this._coders[a].init()};
LZMA.LiteralDecoder.prototype.getDecoder=function(a,b){return this._coders[((a&this._posMask)<<this._numPrevBits)+((b&255)>>>8-this._numPrevBits)]};
LZMA.Decoder=function(){this._outWindow=new LZMA.OutWindow;this._rangeDecoder=new LZMA.RangeDecoder;this._isMatchDecoders=[];this._isRepDecoders=[];this._isRepG0Decoders=[];this._isRepG1Decoders=[];this._isRepG2Decoders=[];this._isRep0LongDecoders=[];this._posSlotDecoder=[];this._posDecoders=[];this._posAlignDecoder=new LZMA.BitTreeDecoder(4);this._lenDecoder=new LZMA.LenDecoder;this._repLenDecoder=new LZMA.LenDecoder;this._literalDecoder=new LZMA.LiteralDecoder;this._dictionarySizeCheck=this._dictionarySize=
-1;this._posSlotDecoder[0]=new LZMA.BitTreeDecoder(6);this._posSlotDecoder[1]=new LZMA.BitTreeDecoder(6);this._posSlotDecoder[2]=new LZMA.BitTreeDecoder(6);this._posSlotDecoder[3]=new LZMA.BitTreeDecoder(6)};LZMA.Decoder.prototype.setDictionarySize=function(a){if(a<0)return false;if(this._dictionarySize!==a){this._dictionarySize=a;this._dictionarySizeCheck=Math.max(this._dictionarySize,1);this._outWindow.create(Math.max(this._dictionarySizeCheck,4096))}return true};
LZMA.Decoder.prototype.setLcLpPb=function(a,b,c){var d=1<<c;if(a>8||b>4||c>4)return false;this._literalDecoder.create(b,a);this._lenDecoder.create(d);this._repLenDecoder.create(d);this._posStateMask=d-1;return true};
LZMA.Decoder.prototype.init=function(){var a=4;this._outWindow.init(false);LZMA.initBitModels(this._isMatchDecoders,192);LZMA.initBitModels(this._isRep0LongDecoders,192);LZMA.initBitModels(this._isRepDecoders,12);LZMA.initBitModels(this._isRepG0Decoders,12);LZMA.initBitModels(this._isRepG1Decoders,12);LZMA.initBitModels(this._isRepG2Decoders,12);LZMA.initBitModels(this._posDecoders,114);for(this._literalDecoder.init();a--;)this._posSlotDecoder[a].init();this._lenDecoder.init();this._repLenDecoder.init();
this._posAlignDecoder.init();this._rangeDecoder.init()};
LZMA.Decoder.prototype.decode=function(a,b,c){var d=0,e=0,i=0,f=0,g=0,k=0,h=0;this._rangeDecoder.setStream(a);this._outWindow.setStream(b);for(this.init();c<0||k<c;){a=k&this._posStateMask;if(this._rangeDecoder.decodeBit(this._isMatchDecoders,(d<<4)+a)===0){h=this._literalDecoder.getDecoder(k++,h);h=d>=7?h.decodeWithMatchByte(this._rangeDecoder,this._outWindow.getByte(e)):h.decodeNormal(this._rangeDecoder);this._outWindow.putByte(h);d=d<4?0:d-(d<10?3:6)}else{if(this._rangeDecoder.decodeBit(this._isRepDecoders,
d)===1){h=0;if(this._rangeDecoder.decodeBit(this._isRepG0Decoders,d)===0){if(this._rangeDecoder.decodeBit(this._isRep0LongDecoders,(d<<4)+a)===0){d=d<7?9:11;h=1}}else{if(this._rangeDecoder.decodeBit(this._isRepG1Decoders,d)===0)b=i;else{if(this._rangeDecoder.decodeBit(this._isRepG2Decoders,d)===0)b=f;else{b=g;g=f}f=i}i=e;e=b}if(h===0){h=2+this._repLenDecoder.decode(this._rangeDecoder,a);d=d<7?8:11}}else{g=f;f=i;i=e;h=2+this._lenDecoder.decode(this._rangeDecoder,a);d=d<7?7:10;a=this._posSlotDecoder[h<=
5?h-2:3].decode(this._rangeDecoder);if(a>=4){b=(a>>1)-1;e=(2|a&1)<<b;if(a<14)e+=LZMA.reverseDecode2(this._posDecoders,e-a-1,this._rangeDecoder,b);else{e+=this._rangeDecoder.decodeDirectBits(b-4)<<4;e+=this._posAlignDecoder.reverseDecode(this._rangeDecoder);if(e<0){if(e===-1)break;return false}}}else e=a}if(e>=k||e>=this._dictionarySizeCheck)return false;this._outWindow.copyBlock(e,h);k+=h;h=this._outWindow.getByte(0)}}this._outWindow.flush();this._outWindow.releaseStream();this._rangeDecoder.releaseStream();
return true};LZMA.Decoder.prototype.setDecoderProperties=function(a){var b,c;if(a.size<5)return false;b=a.readByte();c=b%9;b=~~(b/9);if(!this.setLcLpPb(c,b%5,~~(b/5)))return false;b=a.readByte();b|=a.readByte()<<8;b|=a.readByte()<<16;b+=a.readByte()*16777216;return this.setDictionarySize(b)};LZMA.decompress=function(a,b,c,d){var e=new LZMA.Decoder;if(!e.setDecoderProperties(a))throw"Incorrect stream properties";if(!e.decode(b,c,d))throw"Error in data stream";return true};var CTM=CTM||{};CTM.CompressionMethod={RAW:5718354,MG1:3229517,MG2:3295053};CTM.Flags={NORMALS:1};CTM.File=function(a){this.load(a)};CTM.File.prototype.load=function(a){this.header=new CTM.FileHeader(a);this.body=new CTM.FileBody(this.header);this.getReader().read(a,this.body)};
CTM.File.prototype.getReader=function(){var a;switch(this.header.compressionMethod){case CTM.CompressionMethod.RAW:a=new CTM.ReaderRAW;break;case CTM.CompressionMethod.MG1:a=new CTM.ReaderMG1;break;case CTM.CompressionMethod.MG2:a=new CTM.ReaderMG2}return a};
CTM.FileHeader=function(a){a.readInt32();this.fileFormat=a.readInt32();this.compressionMethod=a.readInt32();this.vertexCount=a.readInt32();this.triangleCount=a.readInt32();this.uvMapCount=a.readInt32();this.attrMapCount=a.readInt32();this.flags=a.readInt32();this.comment=a.readString()};CTM.FileHeader.prototype.hasNormals=function(){return this.flags&CTM.Flags.NORMALS};
CTM.FileBody=function(a){var b=a.triangleCount*3,c=a.vertexCount*3,d=a.hasNormals()?a.vertexCount*3:0,e=a.vertexCount*2,i=a.vertexCount*4,f=0,g=new ArrayBuffer((b+c+d+e*a.uvMapCount+i*a.attrMapCount)*4);this.indices=new Uint32Array(g,0,b);this.vertices=new Float32Array(g,b*4,c);if(a.hasNormals())this.normals=new Float32Array(g,(b+c)*4,d);if(a.uvMapCount){this.uvMaps=[];for(f=0;f<a.uvMapCount;++f)this.uvMaps[f]={uv:new Float32Array(g,(b+c+d+f*e)*4,e)}}if(a.attrMapCount){this.attrMaps=[];for(f=0;f<
a.attrMapCount;++f)this.attrMaps[f]={attr:new Float32Array(g,(b+c+d+e*a.uvMapCount+f*i)*4,i)}}};
CTM.FileMG2Header=function(a){a.readInt32();this.vertexPrecision=a.readFloat32();this.normalPrecision=a.readFloat32();this.lowerBoundx=a.readFloat32();this.lowerBoundy=a.readFloat32();this.lowerBoundz=a.readFloat32();this.higherBoundx=a.readFloat32();this.higherBoundy=a.readFloat32();this.higherBoundz=a.readFloat32();this.divx=a.readInt32();this.divy=a.readInt32();this.divz=a.readInt32();this.sizex=(this.higherBoundx-this.lowerBoundx)/this.divx;this.sizey=(this.higherBoundy-this.lowerBoundy)/this.divy;
this.sizez=(this.higherBoundz-this.lowerBoundz)/this.divz};CTM.ReaderRAW=function(){};CTM.ReaderRAW.prototype.read=function(a,b){this.readIndices(a,b.indices);this.readVertices(a,b.vertices);b.normals&&this.readNormals(a,b.normals);b.uvMaps&&this.readUVMaps(a,b.uvMaps);b.attrMaps&&this.readAttrMaps(a,b.attrMaps)};CTM.ReaderRAW.prototype.readIndices=function(a,b){a.readInt32();a.readArrayInt32(b)};CTM.ReaderRAW.prototype.readVertices=function(a,b){a.readInt32();a.readArrayFloat32(b)};
CTM.ReaderRAW.prototype.readNormals=function(a,b){a.readInt32();a.readArrayFloat32(b)};CTM.ReaderRAW.prototype.readUVMaps=function(a,b){for(var c=0;c<b.length;++c){a.readInt32();b[c].name=a.readString();b[c].filename=a.readString();a.readArrayFloat32(b[c].uv)}};CTM.ReaderRAW.prototype.readAttrMaps=function(a,b){for(var c=0;c<b.length;++c){a.readInt32();b[c].name=a.readString();a.readArrayFloat32(b[c].attr)}};CTM.ReaderMG1=function(){};
CTM.ReaderMG1.prototype.read=function(a,b){this.readIndices(a,b.indices);this.readVertices(a,b.vertices);b.normals&&this.readNormals(a,b.normals);b.uvMaps&&this.readUVMaps(a,b.uvMaps);b.attrMaps&&this.readAttrMaps(a,b.attrMaps)};CTM.ReaderMG1.prototype.readIndices=function(a,b){a.readInt32();a.readInt32();var c=new CTM.InterleavedStream(b,3);LZMA.decompress(a,a,c,c.data.length);CTM.restoreIndices(b,b.length)};
CTM.ReaderMG1.prototype.readVertices=function(a,b){a.readInt32();a.readInt32();var c=new CTM.InterleavedStream(b,1);LZMA.decompress(a,a,c,c.data.length)};CTM.ReaderMG1.prototype.readNormals=function(a,b){a.readInt32();a.readInt32();var c=new CTM.InterleavedStream(b,3);LZMA.decompress(a,a,c,c.data.length)};
CTM.ReaderMG1.prototype.readUVMaps=function(a,b){for(var c=0;c<b.length;++c){a.readInt32();b[c].name=a.readString();b[c].filename=a.readString();a.readInt32();var d=new CTM.InterleavedStream(b[c].uv,2);LZMA.decompress(a,a,d,d.data.length)}};CTM.ReaderMG1.prototype.readAttrMaps=function(a,b){for(var c=0;c<b.length;++c){a.readInt32();b[c].name=a.readString();a.readInt32();var d=new CTM.InterleavedStream(b[c].attr,4);LZMA.decompress(a,a,d,d.data.length)}};CTM.ReaderMG2=function(){};
CTM.ReaderMG2.prototype.read=function(a,b){this.MG2Header=new CTM.FileMG2Header(a);this.readVertices(a,b.vertices);this.readIndices(a,b.indices);b.normals&&this.readNormals(a,b);b.uvMaps&&this.readUVMaps(a,b.uvMaps);b.attrMaps&&this.readAttrMaps(a,b.attrMaps)};CTM.ReaderMG2.prototype.readVertices=function(a,b){a.readInt32();a.readInt32();var c=new CTM.InterleavedStream(b,3);LZMA.decompress(a,a,c,c.data.length);c=this.readGridIndices(a,b);CTM.restoreVertices(b,this.MG2Header,c,this.MG2Header.vertexPrecision)};
CTM.ReaderMG2.prototype.readGridIndices=function(a,b){a.readInt32();a.readInt32();var c=new Uint32Array(b.length/3),d=new CTM.InterleavedStream(c,1);LZMA.decompress(a,a,d,d.data.length);CTM.restoreGridIndices(c,c.length);return c};CTM.ReaderMG2.prototype.readIndices=function(a,b){a.readInt32();a.readInt32();var c=new CTM.InterleavedStream(b,3);LZMA.decompress(a,a,c,c.data.length);CTM.restoreIndices(b,b.length)};
CTM.ReaderMG2.prototype.readNormals=function(a,b){a.readInt32();a.readInt32();var c=new CTM.InterleavedStream(b.normals,3);LZMA.decompress(a,a,c,c.data.length);c=CTM.calcSmoothNormals(b.indices,b.vertices);CTM.restoreNormals(b.normals,c,this.MG2Header.normalPrecision)};
CTM.ReaderMG2.prototype.readUVMaps=function(a,b){for(var c=0;c<b.length;++c){a.readInt32();b[c].name=a.readString();b[c].filename=a.readString();var d=a.readFloat32();a.readInt32();var e=new CTM.InterleavedStream(b[c].uv,2);LZMA.decompress(a,a,e,e.data.length);CTM.restoreMap(b[c].uv,2,d)}};
CTM.ReaderMG2.prototype.readAttrMaps=function(a,b){for(var c=0;c<b.length;++c){a.readInt32();b[c].name=a.readString();var d=a.readFloat32();a.readInt32();var e=new CTM.InterleavedStream(b[c].attr,4);LZMA.decompress(a,a,e,e.data.length);CTM.restoreMap(b[c].attr,4,d)}};CTM.restoreIndices=function(a,b){var c=3;if(b>0){a[2]+=a[0];a[1]+=a[0]}for(;c<b;c+=3){a[c]+=a[c-3];a[c+1]+=a[c]===a[c-3]?a[c-2]:a[c];a[c+2]+=a[c]}};CTM.restoreGridIndices=function(a,b){for(var c=1;c<b;++c)a[c]+=a[c-1]};
CTM.restoreVertices=function(a,b,c,d){for(var e,i,f,g,k,h=new Uint32Array(a.buffer,a.byteOffset,a.length),j=b.divx,m=j*b.divy,p=2147483647,l=0,n=0,o=0,q=c.length;n<q;o+=3){f=e=c[n++];k=~~(f/m);f-=~~(k*m);g=~~(f/j);f-=~~(g*j);i=h[o];if(e===p)i+=l;a[o]=b.lowerBoundx+f*b.sizex+d*i;a[o+1]=b.lowerBoundy+g*b.sizey+d*h[o+1];a[o+2]=b.lowerBoundz+k*b.sizez+d*h[o+2];p=e;l=i}};
CTM.restoreNormals=function(a,b,c){for(var d,e,i,f,g,k,h=new Uint32Array(a.buffer,a.byteOffset,a.length),j=0,m=a.length;j<m;j+=3){d=h[j]*c;e=h[j+1];if(e===0){a[j]=b[j]*d;a[j+1]=b[j+1]*d;a[j+2]=b[j+2]*d}else{i=e<=4?(h[j+2]-2)*1.5707963267948966:(h[j+2]*4/e-2)*1.5707963267948966;e*=c*1.5707963267948966;f=d*Math.sin(e);g=f*Math.cos(i);i=f*Math.sin(i);d*=Math.cos(e);f=b[j+1];e=b[j]-b[j+2];k=Math.sqrt(2*f*f+e*e);if(k>1.0E-20){e/=k;f/=k}a[j]=b[j]*d+(b[j+1]*f-b[j+2]*e)*i-f*g;a[j+1]=b[j+1]*d-(b[j+2]+b[j])*
f*i+e*g;a[j+2]=b[j+2]*d+(b[j]*e+b[j+1]*f)*i+f*g}}};CTM.restoreMap=function(a,b,c){for(var d,e,i=new Uint32Array(a.buffer,a.byteOffset,a.length),f=0,g,k=a.length;f<b;++f){d=0;for(g=f;g<k;g+=b){e=i[g];d+=e&1?-(e+1>>1):e>>1;a[g]=d*c}}};
CTM.calcSmoothNormals=function(a,b){var c=new Float32Array(b.length),d,e,i,f,g,k,h,j,m,p,l,n;l=0;for(n=a.length;l<n;){d=a[l++]*3;e=a[l++]*3;i=a[l++]*3;k=b[e]-b[d];j=b[i]-b[d];h=b[e+1]-b[d+1];m=b[i+1]-b[d+1];g=b[e+2]-b[d+2];p=b[i+2]-b[d+2];f=h*p-g*m;g=g*j-k*p;k=k*m-h*j;h=Math.sqrt(f*f+g*g+k*k);if(h>1.0E-10){f/=h;g/=h;k/=h}c[d]+=f;c[d+1]+=g;c[d+2]+=k;c[e]+=f;c[e+1]+=g;c[e+2]+=k;c[i]+=f;c[i+1]+=g;c[i+2]+=k}l=0;for(n=c.length;l<n;l+=3){h=Math.sqrt(c[l]*c[l]+c[l+1]*c[l+1]+c[l+2]*c[l+2]);if(h>1.0E-10){c[l]/=
h;c[l+1]/=h;c[l+2]/=h}}return c};CTM.isLittleEndian=function(){var a=new ArrayBuffer(2),b=new Uint8Array(a);a=new Uint16Array(a);b[0]=1;return a[0]===1}();CTM.InterleavedStream=function(a,b){this.data=new Uint8Array(a.buffer,a.byteOffset,a.byteLength);this.offset=CTM.isLittleEndian?3:0;this.count=b*4;this.len=this.data.length};
CTM.InterleavedStream.prototype.writeByte=function(a){this.data[this.offset]=a;this.offset+=this.count;if(this.offset>=this.len){this.offset-=this.len-4;if(this.offset>=this.count)this.offset-=this.count+(CTM.isLittleEndian?1:-1)}};CTM.Stream=function(a){this.data=a;this.offset=0};CTM.Stream.prototype.TWO_POW_MINUS23=Math.pow(2,-23);CTM.Stream.prototype.TWO_POW_MINUS126=Math.pow(2,-126);CTM.Stream.prototype.readByte=function(){return this.data[this.offset++]&255};
CTM.Stream.prototype.readInt32=function(){var a=this.readByte();a|=this.readByte()<<8;a|=this.readByte()<<16;return a|this.readByte()<<24};CTM.Stream.prototype.readFloat32=function(){var a=this.readByte();a+=this.readByte()<<8;var b=this.readByte(),c=this.readByte();a+=(b&127)<<16;b=(c&127)<<1|(b&128)>>>7;c=c&128?-1:1;if(b===255)return a!==0?NaN:c*Infinity;if(b>0)return c*(1+a*this.TWO_POW_MINUS23)*Math.pow(2,b-127);if(a!==0)return c*a*this.TWO_POW_MINUS126;return c*0};
CTM.Stream.prototype.readString=function(){var a=this.readInt32();this.offset+=a;return this.data.subarray(this.offset-a,a)};CTM.Stream.prototype.readArrayInt32=function(a){for(var b=0,c=a.length;b<c;)a[b++]=this.readInt32();return a};CTM.Stream.prototype.readArrayFloat32=function(a){for(var b=0,c=a.length;b<c;)a[b++]=this.readFloat32();return a};
